package constv

const (
	TYPES_NULL   = 0
	TYPES_BOOL   = 1
	TYPES_INT    = 2
	TYPES_LONG   = 3
	TYPES_FLOAT  = 4
	TYPES_DOUBLE = 5
	TYPES_STRING = 6
	TYPES_VAR    = 7
	TYPES_ARRAY  = 8
	TYPES_MAP    = 9
	TYPES_BINARY = 10
)
